name: Run PHP test on multiple OS and architectures

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: aarch64
          - os: ubuntu-latest
            arch: x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, json, ffi, msgpack
          tools: composer

      - name: Run Composer
        run: composer install

      - name: Run test
        run: php tests/autotest.php
